spring:
  application:
    name: 33-SB-MS-GREET1-API
  boot:
    admin:
      client:
        url: http://localhost:1111/

management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9091